module.exports = {
  MODULE_NOT_FOUND: 'MODULE_NOT_FOUND',
  MODULE_KEY_ALREADY_EXISTS: 'MODULE_KEY_ALREADY_EXISTS',
  MODULE_SYSTEM_DELETE_BLOCKED: 'MODULE_SYSTEM_DELETE_BLOCKED',
  MODULE_INVALID_KEY: 'MODULE_INVALID_KEY',
  MODULE_INVALID_STATUS: 'MODULE_INVALID_STATUS',
  MODULE_INVALID_CATEGORY: 'MODULE_INVALID_CATEGORY',
  MODULE_NOT_AVAILABLE: 'MODULE_NOT_AVAILABLE',
  MODULE_CORE_DISABLE_BLOCKED: 'MODULE_CORE_DISABLE_BLOCKED',
};
