import { ChangeDetectionStrategy, ChangeDetectorRef, Component, OnDestroy, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { forkJoin, Subject, Subscription } from 'rxjs';
import { take, takeUntil } from 'rxjs/operators';
import dayjs, { Dayjs } from 'dayjs';
import { AdminWeek, TimeEntry, TimesheetService } from 'src/app/modules/shared/services/timesheet.service';
import { WorkforceSidebarUser, WorkforceSummaryUi } from 'src/app/modules/shared/helpers/activity-api.mapper';
import { alert } from 'src/app/modules/shared/services/alert.service';
import { WorkforceDateRange } from './workforce-date-range-filter.component';
import { UsersService } from 'src/app/modules/shared/services/users.service';

type HistoryStatus='all'|'submitted'|'approved'|'rejected';
interface MissingRow { week_start_date:string; week_end_date:string; total_minutes:number; status:'missing'|'draft'; notifiedAt?:Date; notificationCount:number; }
interface EmployeeHistorySummary { weekCount:number; totalMinutes:number; submittedCount:number; approvedCount:number; rejectedCount:number; draftCount:number; }

@Component({selector:'app-workforce-reports-v2',templateUrl:'./workforce-reports-v2.component.html',styleUrls:['./workforce-reports-v2.component.css'],changeDetection:ChangeDetectionStrategy.OnPush})
export class WorkforceReportsV2Component implements OnInit,OnDestroy {
  private readonly destroy$=new Subject<void>(); private historySub?:Subscription;
  range:WorkforceDateRange={startDate:null,endDate:null};
  summary:WorkforceSummaryUi['summary']|null=null;users:WorkforceSidebarUser[]=[];history:AdminWeek[]=[];historySummary:EmployeeHistorySummary|null=null;
  historyTotal=0;historyHasMore=false;selectedId='';statusFilter:HistoryStatus='all';reportSearch='';directoryOpen=false;directoryLoading=true;historyLoading=false;loadingMore=false;error='';
  page=1;readonly pageSize=20;expandedWeekId='';detailCache=new Map<string,TimeEntry[]>();detailLoading=new Set<string>();detailErrors=new Set<string>();
  missingDrawerOpen=false;selectedMissing=new Set<string>();notifying=false;showNotifyDialog=false;rejectWeek:AdminWeek|null=null;rejectReason='';actionKeys=new Set<string>();exporting=false;
  readonly statuses:Array<{value:HistoryStatus;label:string}>=[{value:'all',label:'All statuses'},{value:'submitted',label:'Needs review'},{value:'approved',label:'Approved'},{value:'rejected',label:'Rejected'}];
  constructor(private service:TimesheetService,private usersService:UsersService,private route:ActivatedRoute,private router:Router,private alerts:alert,private cdr:ChangeDetectorRef){}
  ngOnInit():void{this.route.queryParamMap.pipe(take(1),takeUntil(this.destroy$)).subscribe(params=>{const from=params.get('from'),to=params.get('to');if(from&&to&&dayjs(from).isValid()&&dayjs(to).isValid())this.range={startDate:dayjs(from),endDate:dayjs(to)};this.selectedId=params.get('employee')||'';this.statusFilter=(params.get('status') as HistoryStatus)||'all';this.page=Math.max(1,Number(params.get('page')||1));this.loadDirectory();});}
  ngOnDestroy():void{this.historySub?.unsubscribe();this.destroy$.next();this.destroy$.complete()}
  get selectedUser():WorkforceSidebarUser|null{return this.users.find(u=>u.id===this.selectedId)||null}
  get periodLabel():string{return !this.range.startDate||!this.range.endDate?'All History':`${this.range.startDate.format('MMM D')} – ${this.range.endDate.format('MMM D, YYYY')}`}
  get pageCount():number{return Math.max(1,Math.ceil(this.historyTotal/this.pageSize))}
  get visibleHistory():AdminWeek[]{const q=this.reportSearch.trim().toLowerCase();return !q?this.history:this.history.filter(w=>[this.weekLabel(w),w.status,this.duration(w.total_minutes)].some(v=>v.toLowerCase().includes(q)))}
  get pendingCount():number{return this.historySummary?.submittedCount||0}get approvedCount():number{return this.historySummary?.approvedCount||0}get rejectedCount():number{return this.historySummary?.rejectedCount||0}
  get submittedWeeksCount():number{return this.pendingCount+this.approvedCount+this.rejectedCount}
  get missing():MissingRow[]{
    if(!this.selectedId)return[];const end=this.range.endDate||dayjs();const start=this.range.startDate||dayjs().subtract(12,'week');const existing=new Map(this.history.map(w=>[w.week_start_date.slice(0,10),w]));const rows:MissingRow[]=[];let cursor=this.monday(start);const current=this.monday(dayjs());
    while(cursor.isBefore(end)||cursor.isSame(end,'day')){const key=cursor.format('YYYY-MM-DD'),week=existing.get(key);if(cursor.isBefore(current)&&(week?.status==='draft'||!week))rows.push({week_start_date:key,week_end_date:cursor.add(6,'day').format('YYYY-MM-DD'),total_minutes:week?.total_minutes||0,status:week?.status==='draft'?'draft':'missing',notificationCount:0});cursor=cursor.add(7,'day')}return rows.reverse();
  }
  get reportingHealth():string{const user=this.selectedUser;if(!user)return'No activity';if(!user.isActive)return'Inactive';if(this.pendingCount||this.missing.length||this.rejectedCount)return'Needs Attention';if(!this.submittedWeeksCount)return'No Activity';return'Up to Date'}
  get attentionUsers():WorkforceSidebarUser[]{return this.users.filter(u=>u.pending||u.missing||u.rejected)}
  private dateFilters():{startDate?:string;endDate?:string}{return{...(this.range.startDate?{startDate:this.range.startDate.format('YYYY-MM-DD')} :{}),...(this.range.endDate?{endDate:this.range.endDate.format('YYYY-MM-DD')}:{})}}
  loadDirectory():void{this.directoryLoading=true;this.error='';this.usersService.listUsersPage({page:1,limit:100,status:'active',sort_by:'name',sort_order:'asc',includeRoles:false}).pipe(takeUntil(this.destroy$)).subscribe({next:result=>{this.users=(result.data||[]).map((user:any)=>this.toDirectoryUser(user)).sort((a,b)=>a.name.localeCompare(b.name));this.directoryLoading=false;if(this.selectedId&&!this.users.some(u=>u.id===this.selectedId))this.selectedId='';if(!this.selectedId&&this.users[0])this.selectedId=this.users[0].id;if(this.selectedId){this.updateQuery();this.loadHistory(true)}this.cdr.markForCheck()},error:()=>{this.directoryLoading=false;this.error='Unable to load employees.';this.cdr.markForCheck()}})}
  loadHistory(reset=true):void{if(reset)this.historySub?.unsubscribe();if(!this.selectedId){this.history=[];this.historyLoading=false;this.cdr.markForCheck();return}if(reset){this.page=1;this.history=[];this.historyLoading=true;this.historySummary=null}else{if(this.loadingMore||!this.historyHasMore)return;this.loadingMore=true;this.page+=1}this.error='';const employeeId=this.selectedId,page=this.page,status=this.statusFilter==='all'?'submitted,approved,rejected':this.statusFilter;const request=this.service.getWeeksPage({...this.dateFilters(),userId:employeeId,status,page,limit:this.pageSize}).subscribe({next:result=>{if(employeeId!==this.selectedId)return;const rows=result.items as AdminWeek[];this.history=reset?rows:[...this.history,...rows.filter(row=>!this.history.some(existing=>String(existing.id)===String(row.id)))];this.historyTotal=result.total;this.historyHasMore=result.hasMore;this.historySummary=result.summary;this.historyLoading=false;this.loadingMore=false;this.cdr.markForCheck()},error:()=>{if(!reset)this.page=Math.max(1,this.page-1);this.historyLoading=false;this.loadingMore=false;this.error='Unable to load submission history.';this.cdr.markForCheck()}});this.historySub=request}
  chooseEmployee(id:string):void{if(id===this.selectedId)return;this.selectedId=id;this.page=1;this.statusFilter='all';this.reportSearch='';this.expandedWeekId='';this.historySummary=null;this.updateQuery();this.loadHistory(true)}
  changeRange(range:WorkforceDateRange):void{this.range=range;this.page=1;this.historySummary=null;this.expandedWeekId='';this.updateQuery();this.loadHistory(true)}
  changeStatus():void{this.page=1;this.expandedWeekId='';this.updateQuery();this.loadHistory(true)}
  clearFilters():void{this.range={startDate:null,endDate:null};this.statusFilter='all';this.reportSearch='';this.page=1;this.historySummary=null;this.updateQuery();this.loadHistory(true)}
  loadMore():void{this.loadHistory(false)}
  updateQuery():void{this.router.navigate([],{relativeTo:this.route,queryParams:{from:this.range.startDate?.format('YYYY-MM-DD')||null,to:this.range.endDate?.format('YYYY-MM-DD')||null,employee:this.selectedId||null,status:this.statusFilter==='all'?null:this.statusFilter,page:this.page>1?this.page:null},queryParamsHandling:'merge',replaceUrl:true})}
  toggleWeek(week:AdminWeek):void{const key=String(week.id);if(this.expandedWeekId===key){this.expandedWeekId='';return}this.expandedWeekId=key;if(!this.detailCache.has(key))this.loadWeekDetail(week)}
  loadWeekDetail(week:AdminWeek):void{const key=String(week.id);if(!week.id||this.detailLoading.has(key))return;this.detailLoading.add(key);this.detailErrors.delete(key);this.service.getWeekById(week.id).subscribe({next:bundle=>{this.detailCache.set(key,bundle.entries||[]);this.detailLoading.delete(key);this.cdr.markForCheck()},error:()=>{this.detailLoading.delete(key);this.detailErrors.add(key);this.cdr.markForCheck()}})}
  reviewPending():void{this.statusFilter='submitted';this.page=1;this.changeStatus()}
  toggleMissing(row:MissingRow):void{this.selectedMissing.has(row.week_start_date)?this.selectedMissing.delete(row.week_start_date):this.selectedMissing.add(row.week_start_date)}
  confirmNotify():void{if(!this.selectedId||!this.selectedMissing.size||this.notifying)return;this.notifying=true;const keys=[...this.selectedMissing];forkJoin(keys.map(key=>this.service.notifyMissingWeek(this.selectedId,key))).subscribe({next:()=>{this.notifying=false;this.showNotifyDialog=false;this.selectedMissing.clear();this.alerts.responseAlert(`${keys.length} reminder${keys.length===1?'':'s'} sent.`,'success');this.cdr.markForCheck()},error:()=>{this.notifying=false;this.alerts.responseAlert('One or more reminders could not be sent.','error');this.cdr.markForCheck()}})}
  approve(week:AdminWeek,event:Event):void{event.stopPropagation();const key=String(week.id);if(this.actionKeys.has(key)||!confirm(`Approve the report for ${this.weekLabel(week)}?`))return;this.actionKeys.add(key);this.service.approveWeek(week.id!).subscribe({next:()=>{week.status='approved';if(this.historySummary){this.historySummary.submittedCount=Math.max(0,this.historySummary.submittedCount-1);this.historySummary.approvedCount+=1}const user=this.selectedUser;if(user){user.submitted=Math.max(0,user.submitted-1);user.pending=Math.max(0,user.pending-1);user.approved+=1}this.actionKeys.delete(key);this.alerts.responseAlert('Report approved.','success');this.cdr.markForCheck()},error:()=>{this.actionKeys.delete(key);this.alerts.responseAlert('Unable to approve report.','error');this.cdr.markForCheck()}})}
  openReject(week:AdminWeek,event:Event):void{event.stopPropagation();this.rejectWeek=week;this.rejectReason=''}
  confirmReject():void{if(!this.rejectWeek||!this.rejectReason.trim())return;const week=this.rejectWeek,key=String(week.id);this.actionKeys.add(key);this.service.rejectWeek(week.id!,this.rejectReason.trim()).subscribe({next:()=>{week.status='rejected';week.rejection_reason=this.rejectReason;if(this.historySummary){this.historySummary.submittedCount=Math.max(0,this.historySummary.submittedCount-1);this.historySummary.rejectedCount+=1}this.actionKeys.delete(key);this.rejectWeek=null;this.alerts.responseAlert('Report rejected.','success');this.cdr.markForCheck()},error:()=>{this.actionKeys.delete(key);this.alerts.responseAlert('Unable to reject report.','error');this.cdr.markForCheck()}})}
  export():void{if(this.exporting)return;this.exporting=true;setTimeout(()=>{window.print();this.exporting=false;this.cdr.markForCheck()},0)}
  statusLabel(status:string):string{return status==='submitted'?'Pending Review':status==='approved'?'Approved':status==='rejected'?'Rejected':status}
  weekLabel(w:{week_start_date:string;week_end_date:string}):string{return `${dayjs(w.week_start_date).format('MMM D')} – ${dayjs(w.week_end_date).format('MMM D, YYYY')}`}
  duration(m:number):string{const value=Number(m||0);return `${Math.floor(value/60)}h${value%60?` ${value%60}m`:''}`}
  trackWeek(_i:number,w:AdminWeek|MissingRow):string{return String((w as AdminWeek).id||w.week_start_date)}
  private toDirectoryUser(user:any):WorkforceSidebarUser{const name=[user.first_name,user.last_name].filter(Boolean).join(' ').trim()||user.user_name||user.email||'Employee';const parts=name.split(/\s+/);return{id:String(user.id),accountId:user.account_id||null,name,email:user.email||null,status:user.is_active===false?'inactive':'active',role:user.job_title||user.role||'Team Member',initials:(parts.length>1?parts[0][0]+parts[parts.length-1][0]:parts[0]?.[0]||'?').toUpperCase(),isActive:user.is_active!==false,submitted:0,approved:0,rejected:0,pending:0,draft:0,missing:0,totalMinutes:0}}
  private monday(date:Dayjs):Dayjs{return date.startOf('day').subtract((date.day()+6)%7,'day')}
}
