module.exports = {
  MIGRATION_CONFIG_MISSING: 'MIGRATION_CONFIG_MISSING',
  MIGRATION_SOURCE_UNREACHABLE: 'MIGRATION_SOURCE_UNREACHABLE',
  MIGRATION_TARGET_UNREACHABLE: 'MIGRATION_TARGET_UNREACHABLE',
  MIGRATION_STEP_NOT_IMPLEMENTED: 'MIGRATION_STEP_NOT_IMPLEMENTED',
  MIGRATION_MAP_CONFLICT: 'MIGRATION_MAP_CONFLICT',
  MIGRATION_VALIDATION_FAILED: 'MIGRATION_VALIDATION_FAILED',
  USER_EMAIL_MISSING: 'USER_EMAIL_MISSING',
  USER_DUPLICATE_EMAIL_CONFLICT: 'USER_DUPLICATE_EMAIL_CONFLICT',
  ATTACHMENT_PROJECT_MISSING: 'ATTACHMENT_PROJECT_MISSING',
  ATTACHMENT_URL_MISSING: 'ATTACHMENT_URL_MISSING',
};
