module.exports = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ACCOUNT_NOT_FOUND: 'USER_ACCOUNT_NOT_FOUND',
  USER_ACCOUNT_ALREADY_LINKED: 'USER_ACCOUNT_ALREADY_LINKED',
  USER_EMAIL_ALREADY_EXISTS: 'USER_EMAIL_ALREADY_EXISTS',
  USER_USERNAME_ALREADY_EXISTS: 'USER_USERNAME_ALREADY_EXISTS',
  USER_USERNAME_REQUIRED: 'USER_USERNAME_REQUIRED',
  USER_MANAGER_NOT_FOUND: 'USER_MANAGER_NOT_FOUND',
  USER_SELF_MANAGER_NOT_ALLOWED: 'USER_SELF_MANAGER_NOT_ALLOWED',
  USER_HAS_DIRECT_REPORTS: 'USER_HAS_DIRECT_REPORTS',
  USER_INVALID_STATUS: 'USER_INVALID_STATUS',
  USER_PROFILE_NOT_FOUND: 'USER_PROFILE_NOT_FOUND',
};
