module.exports = {
  SOCKET_NOT_INITIALIZED: 'SOCKET_NOT_INITIALIZED',
  SOCKET_AUTH_REQUIRED: 'SOCKET_AUTH_REQUIRED',
  SOCKET_AUTH_INVALID: 'SOCKET_AUTH_INVALID',
  SOCKET_ACCOUNT_INACTIVE: 'SOCKET_ACCOUNT_INACTIVE',
  SOCKET_ROOM_INVALID: 'SOCKET_ROOM_INVALID',
  SOCKET_FORBIDDEN: 'SOCKET_FORBIDDEN',
};
