module.exports = {
  RBAC_ROLE_NOT_FOUND: 'RBAC_ROLE_NOT_FOUND',
  RBAC_PERMISSION_NOT_FOUND: 'RBAC_PERMISSION_NOT_FOUND',
  RBAC_ROLE_KEY_ALREADY_EXISTS: 'RBAC_ROLE_KEY_ALREADY_EXISTS',
  RBAC_PERMISSION_ALREADY_EXISTS: 'RBAC_PERMISSION_ALREADY_EXISTS',
  RBAC_SYSTEM_ROLE_DELETE_BLOCKED: 'RBAC_SYSTEM_ROLE_DELETE_BLOCKED',
  RBAC_SYSTEM_PERMISSION_DELETE_BLOCKED: 'RBAC_SYSTEM_PERMISSION_DELETE_BLOCKED',
  RBAC_ACCOUNT_ROLE_ALREADY_EXISTS: 'RBAC_ACCOUNT_ROLE_ALREADY_EXISTS',
  RBAC_ACCOUNT_ROLE_NOT_FOUND: 'RBAC_ACCOUNT_ROLE_NOT_FOUND',
  RBAC_FORBIDDEN: 'RBAC_FORBIDDEN',
  RBAC_INVALID_ROLE_KEY: 'RBAC_INVALID_ROLE_KEY',
  RBAC_INVALID_PERMISSION_KEY: 'RBAC_INVALID_PERMISSION_KEY',
};
