module.exports = {
  AI_DISABLED: 'AI_DISABLED',
  AI_ACTION_NOT_FOUND: 'AI_ACTION_NOT_FOUND',
  AI_INSUFFICIENT_TOKENS: 'AI_INSUFFICIENT_TOKENS',
  AI_PROVIDER_ERROR: 'AI_PROVIDER_ERROR',
  AI_VALIDATION_FAILED: 'AI_VALIDATION_FAILED',
  AI_JOB_NOT_FOUND: 'AI_JOB_NOT_FOUND',
  AI_JOB_FAILED: 'AI_JOB_FAILED',
  AI_TIMEOUT: 'AI_TIMEOUT',
  AI_DEBUG_REQUIRED: 'AI_DEBUG_REQUIRED',
  AI_FORBIDDEN: 'AI_FORBIDDEN',
};
