module.exports = {
  CLIENT_NOT_FOUND: 'CLIENT_NOT_FOUND',
  CLIENT_NAME_ALREADY_EXISTS: 'CLIENT_NAME_ALREADY_EXISTS',
  CLIENT_CODE_ALREADY_EXISTS: 'CLIENT_CODE_ALREADY_EXISTS',
  CLIENT_INVALID_STATUS: 'CLIENT_INVALID_STATUS',
  CLIENT_INVALID_TYPE: 'CLIENT_INVALID_TYPE',
  CLIENT_HAS_ACTIVE_PROJECTS: 'CLIENT_HAS_ACTIVE_PROJECTS',
};
