module.exports = {
  REPORT_INVALID_PERIOD: 'REPORT_INVALID_PERIOD',
  REPORT_INVALID_DATE_RANGE: 'REPORT_INVALID_DATE_RANGE',
  REPORT_FORBIDDEN: 'REPORT_FORBIDDEN',
  REPORT_USER_NOT_FOUND: 'REPORT_USER_NOT_FOUND',
  REPORT_PROJECT_NOT_FOUND: 'REPORT_PROJECT_NOT_FOUND',
  REPORT_CLIENT_NOT_FOUND: 'REPORT_CLIENT_NOT_FOUND',
};
