module.exports = {
  CONVERSE_FORBIDDEN: 'CONVERSE_FORBIDDEN',
  CONVERSE_NOT_FOUND: 'CONVERSE_NOT_FOUND',
  CONVERSE_MESSAGE_NOT_FOUND: 'CONVERSE_MESSAGE_NOT_FOUND',
  CONVERSE_PARTICIPANT_NOT_FOUND: 'CONVERSE_PARTICIPANT_NOT_FOUND',
  CONVERSE_INVALID_REQUEST: 'CONVERSE_INVALID_REQUEST',
  CONVERSE_DIRECT_SELF: 'CONVERSE_DIRECT_SELF',
  CONVERSE_GROUP_TOO_SMALL: 'CONVERSE_GROUP_TOO_SMALL',
};
