const DEFAULT_MODULES = [
  {
    key: 'auth',
    name: 'Auth',
    description: 'Authentication and session management.',
    category: 'system',
    status: 'active',
    sortOrder: 10,
    routeBase: '/auth',
    isSystem: true,
  },
  {
    key: 'modules',
    name: 'Modules',
    description: 'Platform module registry and activation.',
    category: 'system',
    status: 'active',
    sortOrder: 20,
    routeBase: '/modules',
    isSystem: true,
  },
  {
    key: 'rbac',
    name: 'RBAC',
    description: 'Roles and permissions (coming in Module 3).',
    category: 'system',
    status: 'inactive',
    sortOrder: 30,
    routeBase: '/rbac',
    isSystem: true,
  },
  {
    key: 'users',
    name: 'Users',
    description: 'Employee and user profiles.',
    category: 'core',
    status: 'inactive',
    sortOrder: 40,
    routeBase: '/users',
    isSystem: true,
  },
  {
    key: 'clients',
    name: 'Clients',
    description: 'Client companies and contacts.',
    category: 'core',
    status: 'inactive',
    sortOrder: 50,
    routeBase: '/clients',
    isSystem: true,
  },
  {
    key: 'projects',
    name: 'Projects',
    description: 'Project tracking and delivery.',
    category: 'work_management',
    status: 'inactive',
    sortOrder: 60,
    routeBase: '/projects',
    isSystem: true,
  },
  {
    key: 'assignments',
    name: 'Assignments',
    description: 'Project team assignments and allocations.',
    category: 'work_management',
    status: 'inactive',
    sortOrder: 70,
    routeBase: '/assignments',
    isSystem: true,
  },
  {
    key: 'budgets',
    name: 'Budgets',
    description: 'Project budgets and hour buckets.',
    category: 'work_management',
    status: 'inactive',
    sortOrder: 80,
    routeBase: '/budgets',
    isSystem: true,
  },
  {
    key: 'activity',
    name: 'Activity',
    description: 'Time tracking and activity logging.',
    category: 'work_management',
    status: 'inactive',
    sortOrder: 90,
    routeBase: '/activity',
    isSystem: true,
  },
  {
    key: 'tasks',
    name: 'Tasks',
    description: 'Task boards and workflow.',
    category: 'work_management',
    status: 'inactive',
    sortOrder: 100,
    routeBase: '/tasks',
    isSystem: true,
  },
  {
    key: 'converse',
    name: 'Converse',
    description: 'Team messaging and conversations.',
    category: 'communication',
    status: 'active',
    sortOrder: 110,
    routeBase: '/converse',
    isSystem: true,
  },
  {
    key: 'reports',
    name: 'Reports',
    description: 'Dashboards and reporting.',
    category: 'reporting',
    status: 'inactive',
    sortOrder: 120,
    routeBase: '/reports',
    isSystem: true,
  },
];

module.exports = DEFAULT_MODULES;
