/**
 * Built-in pts_modules registry.
 * status on create only — seedSystemModules must not overwrite status on existing rows.
 */
const DEFAULT_MODULES = [
  {
    key: 'auth',
    name: 'Auth',
    description: 'Authentication and session management.',
    category: 'system',
    status: 'active',
    sortOrder: 10,
    routeBase: '/auth',
    isSystem: true,
  },
  {
    key: 'modules',
    name: 'Modules',
    description: 'Platform module registry and activation.',
    category: 'system',
    status: 'active',
    sortOrder: 20,
    routeBase: '/modules',
    isSystem: true,
  },
  {
    key: 'rbac',
    name: 'RBAC',
    description: 'Roles and permissions.',
    category: 'system',
    status: 'active',
    sortOrder: 30,
    routeBase: '/rbac',
    isSystem: true,
  },
  {
    key: 'dashboard',
    name: 'Dashboard',
    description: 'Admin and user home dashboards.',
    category: 'core',
    status: 'active',
    sortOrder: 35,
    routeBase: '/dashboard',
    isSystem: true,
  },
  {
    key: 'users',
    name: 'Users',
    description: 'Employee and user profiles.',
    category: 'core',
    status: 'active',
    sortOrder: 40,
    routeBase: '/users',
    isSystem: true,
  },
  {
    key: 'clients',
    name: 'Clients',
    description: 'Client companies and contacts.',
    category: 'core',
    status: 'active',
    sortOrder: 50,
    routeBase: '/clients',
    isSystem: true,
  },
  {
    key: 'projects',
    name: 'Projects',
    description: 'Project tracking and delivery.',
    category: 'core',
    status: 'active',
    sortOrder: 60,
    routeBase: '/projects',
    isSystem: true,
  },
  {
    key: 'assignments',
    name: 'Assignments',
    description: 'Project team assignments and allocations.',
    category: 'work_management',
    status: 'active',
    sortOrder: 70,
    routeBase: '/assignments',
    isSystem: true,
  },
  {
    key: 'budgets',
    name: 'Budgets',
    description: 'Project budgets and hour buckets.',
    category: 'work_management',
    status: 'active',
    sortOrder: 80,
    routeBase: '/budgets',
    isSystem: true,
  },
  {
    key: 'activity',
    name: 'Activity',
    description: 'Time tracking and activity logging (legacy timesheet base).',
    category: 'core',
    status: 'active',
    sortOrder: 90,
    routeBase: '/activity',
    isSystem: true,
  },
  {
    key: 'tasks',
    name: 'Tasks',
    description: 'Task boards and workflow.',
    category: 'work_management',
    status: 'inactive',
    sortOrder: 100,
    routeBase: '/tasks',
    isSystem: true,
  },
  {
    key: 'converse',
    name: 'Converse',
    description: 'Team messaging and conversations.',
    category: 'communication',
    status: 'inactive',
    sortOrder: 110,
    routeBase: '/converse',
    isSystem: true,
  },
  {
    key: 'clock_activity',
    name: 'Clock Activity',
    description: 'Live clock-in / clock-out time tracking (optional feature).',
    category: 'work_management',
    status: 'inactive',
    sortOrder: 115,
    routeBase: '/clock',
    isSystem: true,
  },
  {
    key: 'reports',
    name: 'Reports',
    description: 'Dashboards and reporting.',
    category: 'reporting',
    status: 'inactive',
    sortOrder: 120,
    routeBase: '/reports',
    isSystem: true,
  },
  {
    key: 'daily_flow',
    name: 'Daily Flow',
    description: 'User-first daily planning, goals, catchups, mood, and reflections.',
    category: 'work_management',
    status: 'inactive',
    sortOrder: 125,
    routeBase: '/daily-flow',
    isSystem: true,
  },
  {
    key: 'discuss_flow',
    name: 'DiscussFlow',
    description: 'Topic-first discussions that become requirements, decisions, and documents.',
    category: 'communication',
    status: 'inactive',
    sortOrder: 130,
    routeBase: '/discuss-flow',
    isSystem: true,
  },
];

module.exports = DEFAULT_MODULES;
