module.exports = {
  BOARD_SHARE_NOT_FOUND: 'BOARD_SHARE_NOT_FOUND',
  BOARD_SHARE_CLIENT_NOT_FOUND: 'BOARD_SHARE_CLIENT_NOT_FOUND',
  BOARD_SHARE_PROJECT_NOT_FOUND: 'BOARD_SHARE_PROJECT_NOT_FOUND',
  BOARD_SHARE_PROJECT_CLIENT_MISMATCH: 'BOARD_SHARE_PROJECT_CLIENT_MISMATCH',
  BOARD_SHARE_ALREADY_ACTIVE: 'BOARD_SHARE_ALREADY_ACTIVE',
  BOARD_SHARE_ACCESS_DENIED: 'BOARD_SHARE_ACCESS_DENIED',
  BOARD_SHARE_EXPIRED: 'BOARD_SHARE_EXPIRED',
  BOARD_SHARE_REVOKED: 'BOARD_SHARE_REVOKED',
  BOARD_SHARE_INVALID_ROLE: 'BOARD_SHARE_INVALID_ROLE',
  BOARD_SHARE_INVALID_STATUS: 'BOARD_SHARE_INVALID_STATUS',
};
